# -*- coding: utf-8 -*-
"""Exercise1_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZJ3RfdT5450rmBDDosMmKaca9AZGEzb
"""

import seaborn as sns
import pandas as pd 
import numpy as np
tips = pd.read_csv("data/tips.csv")
X = tips.drop('tip', axis=1)
X.head(10)

X.shape

Y = tips['tip']
Y.head(10)

Y.shape